apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-workshop-1
spec:
  title: Spring on Kubernetes
  description: A workshop for Spring on Kubernetes
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/springone-tour-2021/lab-workshop-1
  content:
    image: jdk11-environment:*
    files: https://github.com/springone-tour-2021/lab-workshop-1
  session:
    namespaces:
      budget: large
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
