apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-spring-on-kubernetes
spec:
  title: Spring on Kubernetes
  description: Spring on Kubernetes workshop
  workshop:
    image: jdk17-environment:*
    files:
    - image:
        url: $(image_repository)/spring-on-kubernetes-files:latest
      includePaths:
      - /workshop/**
      - /exercises/**
  session: 
    dashboards:
      - name: Petclinic
        url: "http://$(session_namespace)-petclinic.$(ingress_domain)/"
    namespaces:
      limits:
        min:
          cpu: 50m
          memory: 32Mi
        max:
          cpu: 1000m
          memory: 2Gi
        defaultRequest:
          cpu: 50m
          memory: 1Gi
        default:
          cpu: 500m
          memory: 1Gi
      budget: large
      security:
        policy: baseline
    resources:
      memory: 4Gi
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
